### ISSUE TITLE
Assign employees to orders

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#1]
We are not sure how employees are supposed to be assigned a particular harvest. Is this something managers will do on their own (ie. look at a list of upcoming harvests and manually assign them), or something the app should automatically do?

If the app is automatically assigning harvests to employees, on what grounds does it make that decision? Days and hours the employee is scheduled? Specific gardens they are assigned to? Whoever is closest to the particular harvest (like uber)? Some of these are more complicated than others. We need some insight into how the employee management aspect of this over at GardenHub is going to work to make some decisions.

Could you think about this and get back to us by next weekend if possible?

Thanks!

**Comment by marykatefain** [comment]
Tagging in @JenniferGold and @ashleyseiver on this one! :)

**Comment by JenniferGold** [comment]
Will look at this on Tuesday!

**Comment by JenniferGold** [comment]
Will look at this on Tuesday!

**Comment by marykatefain** [comment]
Awesome, thanks!

**Comment by marykatefain** [comment]
## Notes from call:

- 1 garden has 1 employee (default) ex. Max
- If no harvests, they still go to do dedicated City Harvest Plots tending (if they have one)
- They also do general tending. Large gardens = every day, Small gardens = every few days
- City Harvest Plots is dedicated to the organization, and 100% is donated always (GM enter this)
- City Harvest the program that GH donates to, in exchange for garden support
- "gleaning" = harvesting crops and donating them, most large gardens have dedicated plots already
- Garden managers manage employees, and should be able to re-assign default gardener depending on situations

**- Q: do employees go 7 days a week? What if a harvest is just scheduled for 1 day?**
- Weather??
- Some drop off locations open only M-F, 9-5
- Doesn't matter what day it's done as long as it's done
- Gardeners have to use judgement call to get stuff at the right time
- Can the app understand days not available?

DROPS OFFS?!
- Most gardens have an assigned drop off point, by area

## Ideas for later:
- Facilitate GMs getting volunteers for jobs
- Social stuff
- Potential drop off point: farmer's market stand for selling

**Comment by alexgleason** [comment]
I've implemented User.get_picker_orders() which returns all Order objects from every plot in each garden the user as assigned as a "picker" on.
