### ISSUE TITLE
Provide error for Picker who tries to Cancel Order

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#104]
When a Picker user tries to Cancel an order that they are picking, it simply logs them out instead of telling them they don't have permission. Honestly not sure why they see this option anyways? It's the only option under the settings icon

**Comment by alexgleason** [comment]
Oh, interesting. Pickers shouldn't see that option.

**Comment by alexgleason** [comment]
I fixed it in 7792e75435a55ae53d39d533a0c58d82e166e862 but I'm not happy about the way I had to do it
