### ISSUE TITLE
Create some pleasing illustrations

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#106]
For one, instead of "Welcome, Alex!" I'd like to see a faint illustrated skyline or something of the sort in the back. I think we could really benefit from adding some character to the design.

Specifically, I love the illustrations on the [old Dropbox homepage](https://web.archive.org/web/20170215001225/https://www.dropbox.com/).

**Comment by JenniferGold** [comment]
I like this idea.

Faint illustrated skyline sounds good for now.

**Comment by alexgleason** [comment]
![screen shot 2018-02-26 at 14 53 11](https://user-images.githubusercontent.com/3639540/36691972-c77f4bb4-1b04-11e8-85ca-d6dc1a3bdd02.png)

We have this little sunrise, which I think is enough for now.
