### ISSUE TITLE
Reporting on Harvest completion

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#13]
- How many lbs of each crop got delivered to drop off point 
- Total lb per crop by garden

- Checkout at end of garden to record lbs
- Crop names do not need to be linked to plot crop name, just general

**Comment by marykatefain** [comment]
- If plot is missed one day, need info

- If nothing picked day before harvest expires, send reminder to GM and Gardener?

**Comment by alexgleason** [comment]
Closing since it's really notes and not an action item. Feel free to repost under [discussions](https://github.com/orgs/HarvestHub/teams/gardenhub) or save elsewhere.
