### ISSUE TITLE
Crop pics saving into root?

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#14]
They were originally uploaded to /static/images/crop_pics and now are appearing in the root... I imagine the database is saving them there somehow.

**Comment by alexgleason** [comment]
This is actually a setting in Django. Standard practice for uploaded files is to put it in a directory called `media` (in the root, next to `static`) and gitignore it.

This is configured by the `MEDIA_ROOT` setting. See: https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-MEDIA_ROOT

Check out `settings/base.p`y, towards the bottom near where `STATIC_ROOT` is defined.

**Comment by marykatefain** [comment]
Ahh okay, thank you! I will configure this.

**Comment by alexgleason** [comment]
You accidentally committed these pics to the design branch

**Comment by marykatefain** [comment]
It wasn't a mistake, I did it before you posted your message because I thought they should be in that folder, haha. I'll fix it when I get to this issue :)

**Comment by alexgleason** [comment]
Um whoops, I removed the pics from the repo but hadn't actually fixed the settings. Fixed in 714b259b07ff6b0390e86b8d73b86415d7d601ff.
