### ISSUE TITLE
Let pickers attach a comment to their pick

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#148]
So we agreed that a picker should have the ability to write something about their pick when it happens. This will allow pickers to add more information about their pick that we aren't capturing with the crop selector alone, eg any potential problems as well as information about how much they picked. We're using a general field in lieu of having more clearly defined fields because we don't know exactly what we want yet, which is fine.

I do need to answer this, though: **where else does this comment show up?** In the email notification to the requester? Can a picker edit their comment somehow (there's currently no way for a picker to review their picks)? etc etc

**Comment by marykatefain** [comment]
I think it should show:
 - On the activity field of the order
 - Any relevant email notifications

I don't think they need to edit it right now. Maybe we can add that functionality later.
