### ISSUE TITLE
Design user profile screens

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#25]
If we want to facilitate messaging between users we need some sort of profile screen for users. It can be as limited or complex as we'd like, possibly with privacy settings.

**Comment by marykatefain** [comment]
Created a basic user profile screen. We'll want to probably make better decisions down the line about what info should be on here depending on what the purpose is. I think this is a good start for now!

![screenshot from 2017-12-01 14 20 24](https://user-images.githubusercontent.com/17955536/33499521-322d37f6-d6a3-11e7-80b1-a2bedd37ba17.png)
