### ISSUE TITLE
Staticfiles not being deployed properly

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#26]
We're using the heroku-python-buildpack which automatically runs collectstatic, but I noticed we always have to run it again manually after each deploy. This may be because I've mounted the static files into the host and am serving them from nginx on the host. The Python buildpack compiles them into /tmp and then copies them over? Not sure what's going on here.

Anyway, for now we can use this:

```
ssh dokku@candlewaster.co run gardenhub python manage.py collectstatic --noinput
```

**Comment by alexgleason** [comment]
I added a deploy script to the make file that pushes to dokku and runs the above in a single command

```
make deploy
```

Still not closing this because I want to fix the underlying issue.

**Comment by marykatefain** [comment]
Lovely, this will be very useful!

**Comment by alexgleason** [comment]
I think we should look into using [WhiteNoise](http://whitenoise.evans.io/en/stable/). I've seen it before but never used it. It doesn't require all this hanky-panky surrounding mounting static files and serving them from nginx. Ideally I want this app to go from 0 to 100 in terms of deployment with no extra configuration.

This blog post might also be useful to us: [How to deploy Django on Dokku](https://www.stavros.io/posts/deploy-django-dokku/)

**Comment by alexgleason** [comment]
I attempted to add in whitenoise. We'll see how this pans out on the next deploy.

**Comment by alexgleason** [comment]
The last few commits improve the deploy pipeline a lot. Aside from some normal config stuff it pretty much does go from 0 to 100 on deploy now.

Local development can be improved but I did add the `make devserver` which launches the runserver command within a docker container without any extra configuration. If you're ever running into issues I suggest trying that.
