### ISSUE TITLE
Create icons to represent some common data types (garden, plot, etc)

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#27]
In #20 I made some mockups with fields where you can select a garden or plot.

I used a map marker to represent a plot, and a map icon to represent a garden. Maybe we could do something more relevant to the actual data types though.

**Comment by alexgleason** [comment]
Here's an icon set I came up with. Thoughts?

![screenshot from 2017-12-14 15 10 09](https://user-images.githubusercontent.com/3639540/34012260-1e6a29ca-e0e1-11e7-93cc-9be95ac7d666.png)

![screenshot from 2017-12-14 15 10 27](https://user-images.githubusercontent.com/3639540/34012271-283fa1d2-e0e1-11e7-9f4b-37c7ac0a4645.png)

**Comment by marykatefain** [comment]
I like these, especially the order one! I think the symbols accurately represent the data, which is an improvement over the default ones we've been using.

My only concerns with the garden and plot icons is they may not be clear what they are. I'm not sure I would have figured out the fence if I hadn't seen it over your shoulder, and the plot one is clear when it's opaque but hard to tell when it's grayed-out.

**Comment by alexgleason** [comment]
Alright well I just pushed them up in 11fa6af8f8bf372168be6fb320818cef62f2a2f9. We can go back and improve them later if we want.

**Comment by alexgleason** [comment]
P.S. I used IcoMoon to create the icon font: https://icomoon.io/app/

**Comment by alexgleason** [comment]
I just created a much better plot icon. The other one was really bothering me.

![screenshot from 2018-02-07 18 44 06](https://user-images.githubusercontent.com/3639540/35947650-f0713730-0c36-11e8-9389-dfbe3f8e0163.png)
