### ISSUE TITLE
How to make the crop icons on Submit Order

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#29]
**Directions from Alex:**

1. For each crop, create an element. That element will have two children. One child will be a checkbox input whose name attribute is in a format like` crop_<cropId>. eg name="crop_4"`. The second child will be the tappable icon.

2. Use CSS to hide the checkbox. Then, write javascript so that when the icon is tapped, the sibling checkbox of the tapped icon is toggled.

3. Finally, write CSS using the adjacent selector (+) so you can style the thumbnail based on whether the sibling checkbox is on or off.

When the form is submitted, it will submit the checkbox data despite it being invisible on the page.
essentially, use javascript to manipulate invisible checkbox data

For the CSS part, you'll want something like so:

```
.crop input[type="checkbox"]:checked + .icon { /* styles to show when the crop is selected */ }
yes
```

https://stackoverflow.com/a/30379525

**Comment by alexgleason** [comment]
This seems to be working per 1aaabf31d07d3a8f3dc6ced89c00d972a6440cb3
