### ISSUE TITLE
Fix home screen styles (after moving into Semantic UI)

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#37]
H3's are now big and they're the default font for Semantic UI.

I think we need to convert them into div's or something and maybe use Saira Extra Condensed. As a sidenote, I noticed we're also using Open Sans Condensed... not sure we need so many fonts, let's try to include no more than 1 additional font to Semantic UI.

We may be able to handle some of the elements a bit differently too, like using ui buttons for the order thing or something.

**Comment by marykatefain** [comment]
This was pretty much resolved when we moved to the card theme for open orders and took it off the home page. We may to talk about fonts in a general branding convo
