### ISSUE TITLE
Rethink the home screen

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#40]
Right now the home screen is basically a "view orders" screen. It just lists the user's orders, sorted ascending by the time it was created. I don't think this is useful enough, nor the first thing a user wants to see.

Particularly, I anticipate a user wanting to see *the currently active orders* first, perhaps sorted by their start date. Other orders can be obfuscated behind an "order history" button which takes the user to a view with their entire order history.

Perhaps they shouldn't even be formatted as "orders" but instead it should show the current date alongside a list of plots being watched for harvest. I'm not sure exactly how to present this in the most useful way. Maybe it could also show the current weather, info about the last harvest, or some other reassuring data.

I think in general a gardener/manager will view the homescreen of the app for two major reasons:

1. The place/cancel an order
2. Reassurance that everything is going as planned

We can solve the first problem with a big purple button to make a new order. For the second problem, how do we address the users' potential anxieties? What information will soothe them? What information will make them feel empowered by the app?

**Comment by marykatefain** [comment]
I'm removing this from 1.0.0

**Comment by alexgleason** [comment]
I couldn't help it, it was really bothering me, so here's what I did:

![screen shot 2018-02-07 at 20 16 22](https://user-images.githubusercontent.com/3639540/35950580-3da621b0-0c45-11e8-97e0-eaaf7c8eb480.png)

If you don't have any orders, it just doesn't show that bit:

![screen shot 2018-02-07 at 20 28 37](https://user-images.githubusercontent.com/3639540/35950632-7ff854de-0c45-11e8-9e39-64a4e22f9b45.png)

**Comment by alexgleason** [comment]
We may rethink this screen again in the future, but for now I'll close it.
