### ISSUE TITLE
Include a "select all" button to allow all crops to be Harvested for an Order

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#46]
I'm actually questioning our UI choices to begin with. Under what condition would someone *ever* not want to harvest all their crops?

Let's figure that out. If we decide it's needed, let's include a "select all" button or something that lets users choose all their crops instead of tapping them all one by one.

**Comment by marykatefain** [comment]
I'd like to go ahead and implement a "select all" button which will select all of the crops in the plot. This can just show to the Picker as listing each crop individually independent from whether they were clicked on by one or through the "select all" button.

I think if we want to change how we do it later that's okay, but we know we'll need something like this so let's move forward.

**Comment by JenniferGold** [comment]
I like that idea!

**Comment by alexgleason** [comment]
![screen shot 2018-01-11 at 17 04 27](https://user-images.githubusercontent.com/3639540/34849747-7ed34924-f6f1-11e7-9e60-1f75d94102d2.png)

Added in 264b9d0bfeea9160443738f831448fa04ae140c3

**Comment by marykatefain** [comment]
Nice! Thank you!

**Comment by JenniferGold** [comment]
Thanks!
