### ISSUE TITLE
Add functionality to Edit and Delete Profile buttons

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#48]
These buttons should do these things eventually. Screenshot for context:

![screenshot from 2017-12-01 14 20 24](https://user-images.githubusercontent.com/17955536/33499909-e55b34da-d6a4-11e7-84aa-3fd73c285c11.png)

**Comment by alexgleason** [comment]
The ability to edit an account was added a while back. You can now deactivate your account via d1040bbca14de8ec59268035eac13e0473c1d27b.
