### ISSUE TITLE
Handle case when Plot has no crops

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#49]
If a plot has no crops an order cannot be placed.

I'm wondering if we need to rethink how crops work, per #46

**Comment by marykatefain** [comment]
I feel like this is actually under control now. The user has 3 things they can do at this point:

1) Toggle the "harvest everything" button
2) Click the "add crops" button and fill in their plot before returning to creating an order
3) Leave crops blank, but include a comment detailing their request

Any of these should give the picker the info they need. #1 and #2 currently work, but #3 returns an error to select the crops. I think we need to just allow them to submit an order with no crops at this point.


![screenshot from 2018-01-25 17 53 24](https://user-images.githubusercontent.com/17955536/35416831-ac9faa34-01f8-11e8-8dc5-66ff1fd772f5.png)

**Comment by alexgleason** [comment]
You're right. We'll just need to ensure that the form responds reasonably depending on what the user inputs before hitting submit in #62.
