### ISSUE TITLE
Handle case where two orders on the same plot have an overlapping timeframe

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#50]
For example, say we have "plot 3" in "Garden A".

A user schedules a Harvest for October 5 to October 9 on plot 3. Then, a user schedules a Harvest for October 5 to October 9 on plot 3. How do we handle that?

Also, a user schedules a Harvest for October 5 to October 9 on plot 3. then, a user schedules a Harvest for October 6 to October 10 on plot 3. How do we handle that?

**Comment by marykatefain** [comment]
I suggest it just shoot back an error saying there is a conflict with a current order, and then provide a button and direct them to edit or cancel that order directly.

**Comment by alexgleason** [comment]
That's sort of what I was thinking. Assuming validation fails there and overlapping orders make it into the database, what should the picker see? By default it would present them with both orders on the same plot.

**Comment by marykatefain** [comment]
I think it's fine for the picker to see both orders if validation fails. Let's just focus on the validation. Looks like this also comes back to #62.

**Comment by alexgleason** [comment]
3a33837bfb8575da3fe27be906412de0ff0974d9 prevents users from creating an order if there's already an active order on that plot within the timeframe specified. It helpfully suggests that users cancel their open order(s) or enter a different date range.

![screen shot 2018-01-27 at 21 22 51](https://user-images.githubusercontent.com/3639540/35478335-429a619a-03a8-11e8-8bcf-f0d1bd5f034c.png)

This obviously isn't ideal, but it's a conservative approach until we figure out what to do with #92.
