### ISSUE TITLE
Allow crops to be entered into an order in a more free-form way

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#52]
Per #46 and #49 I think we really need more information about how crops on plots will change over time and think critically about the best UI and database implementation to achieve that. I consider this a blocker right now.

Right now, crops are actually a *property* of a Plot. For example, Plot 3 in Spring Garden contains tomatoes, lettuce, and oranges. This data is stored about the Plot in the database.

This system requires the gardener to manually edit the Plot any time a new crop is added or removed from the Plot. They must do this *before* they try to place an order. This is counter-intuitive and a bad user experience. When someone places an order, they already have in mind which crops they want harvested. I imagine most of the time it will be "all of them." Am I correct?

We chose to do it this way for several reasons but I am now second guessing them. I'm thinking the best way to place an order may be for the user to type the name of each crop *or* to let them pick "harvest all crops". This allows for flexibility. We can also have an auto-complete feature that makes it easy for them to do this.

**Comment by marykatefain** [comment]
I think they should be able to edit the plot's crops on the Order screen like we talked about, but otherwise it seems pretty much fine to me the way it is. Many users will choose "all", but they shouldn't have to.

**Comment by alexgleason** [comment]
Okay, well does choosing "all" send "all" into the Order model? Or does it just automatically send all crops on the plot into the Order?

The distinction is important because if we just send "all" we will not be able to get statistics about the crops being ordered (although we can about crops being harvested since the picker will input that information). There are other implications to this I'm only loosely wrapping my mind around right now.

**Comment by marykatefain** [comment]
Closing in lieu of #90
