### ISSUE TITLE
Handle case where user is removed from all Plots/Gardens prior to activating their account

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#53]
1. A new user's email address is added to a Plot or Garden.
2. An invite is dispatched to that user with a URL to activate their account.
3. The user is removed from all Plots and Gardens prior to activating their account.
4. ???

What should happen?

As it stands, it will still allow them to make an account, but the site won't be accessible to them since they can't edit any Garden or Plot.

**Comment by marykatefain** [comment]
Yeah I think when they log in it would just say "You aren't assigned to any plots or gardens. Join a community garden near you to get involved, or contact your garden manager if you think this is an error."

**Comment by alexgleason** [comment]
Fixed, it just looks like this:

![screen shot 2018-02-26 at 15 13 32](https://user-images.githubusercontent.com/3639540/36692950-a6c140d2-1b07-11e8-9008-8c1c33e46837.png)
