### ISSUE TITLE
Deleting a garden has catastrophic consequences

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#54]
If a user deletes a garden, all plots within the garden will also be deleted. This will effectively force all users out of the app who grow exclusively on plots in that garden, since there is nothing left for them to manage.

I'm wondering if garden managers should be allowed to delete gardens, or if this privilege should be reserved only for admins.

**Comment by marykatefain** [comment]
Maybe there is an "active" vs "inactive" state where it wouldn't delete anything, but all orders and changes are essentially on hold for now? Then with approval of an admin gardens could be permanently deleted.

**Comment by alexgleason** [comment]
OK, this will work. It's also crucial that no plots or gardens *ever* be deleted because Orders refer to them by a foreign key so deleting them forever would effectively damage order history.

**Comment by alexgleason** [comment]
I made a new issue, #96, specifically for the UI side of this. This issue was originally about that, but the order/pick part is more catastrophic.

In 5d9f4e4fe6d6e19244cfeadef497ce02b6665472 I prevented items related to picks and orders from being able to be deleted.
