### ISSUE TITLE
Change "Harvest" to "Pick"

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#56]
I'm thinking that now that we call the independent contractors "pickers" in the app, it only makes sense to refer to the act of harvesting crops as a "pick." After all, pickers "pick". Why should pickers "harvest"? It's literally in the name.

@marykatefain do you see any issue with the semantics behind this or should we do it?

Also:

1. Harvest is a more complicated word. Sure it provides more context, but it's not intuitive regardless.
2. Pickers will be be literally picking crops with their hands. Harvest suggests there may be tools like sickles or machinery involved. We can represent a "Pick" using closed fist surrounding a stalk (think: food not bombs).
3. Pick is cuter.

**Comment by marykatefain** [comment]
Yeah this is fine

**Comment by alexgleason** [comment]
Okay, fixed in 7abacb7ac85befd8c984e23ed64a065193b71930
