### ISSUE TITLE
Disallow users to select a date prior to today on the Create Order form

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#59]
When creating an order, the user shouldn't be allowed to select an order in the past.

Ideally this would be enforced on both the model level and the view level.

**Comment by marykatefain** [comment]
I also ran into this. When you try to select a date prior to today the order doesn't seem to get submitted properly, but there is no error returned to the user. 

Also fro a UI standpoint the dates could be grayed out to indicate that they can't be clicked.

**Comment by marykatefain** [comment]
#62

**Comment by alexgleason** [comment]
1b10b309b13b9140ccf8e4f38e87b111bfd00f26 provides both front-end and back-end validation for this.
