### ISSUE TITLE
Refine form validation

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#62]
The forms are a bit messy in how they validate the entered data. We'd like to validate it all on the front-end prior to submission if possible, and give adequate feedback as to where any issues lie.

Also the "Create Pick" form in particular needs to have a success message and possibly redirect upon submission.

- [x] LoginView
- [x] AccountSettingsView
- [x] AccountActivateView
- [x] OrderCreateView
- [x] PickCreateView
- [x] PlotCreateView
- [x] PlotUpdateView
- [x] GardenUpdateView

**Comment by alexgleason** [comment]
I'm gonna say that #94 is a precursor to this.

**Comment by marykatefain** [comment]
^ We should allow a user to submit an order form with no crops as long as:

1) "pick everything" is toggled ON
or 2) They leave a comment

Currently attempting to submit an order with no crops returns an error.

**Comment by marykatefain** [comment]
See #50 and #59 for related form validation issues

**Comment by alexgleason** [comment]
Done
