### ISSUE TITLE
"Order" vs "Harvest" language

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#68]
I know we moved away from the "harvest" language because it was not specific to the action the user was taking, but I'm wondering if "order" implies an exchange of money which may be confusing. Is there a way to can integrate the harvest language back, or maybe add something on the homepage that makes it clear what exactly is happening? Not sure off the top of my head what this could look like...

**Comment by alexgleason** [comment]
We actually moved from Harvest to Pick. Order was always "Order."

After all, a "harvest" is when crops are actually harvested. If anything, I'd call it a "Pick Order" or "Harvest Order"

**Comment by marykatefain** [comment]
I'm less concerned with what it's called in the code vs what the user sees, especially on the home page. For example, what if that button said "Schedule a Harvest" again instead of "New Order"? 

We know they are placing an order, but the button will make more sense to them. What was wrong with this language?

![gardener_home_wf](https://user-images.githubusercontent.com/17955536/34782791-bcd1f928-f5f7-11e7-93b0-d39d5b2a5077.png)

**Comment by alexgleason** [comment]
Is "Schedule a Pick" wrong?

**Comment by marykatefain** [comment]
Well pick is a gross and general word. Also it's HarvestHub, not PickHub. 

I'd say "Harvest" is a more specific word for pick that tells what you are picking - crops.

**Comment by alexgleason** [comment]
We have a ton of language referring to "Orders", what do you suggest we do?

eg, "Your Orders", "Your Active Orders", "You haven't placed any orders"

**Comment by marykatefain** [comment]
Okay, we can leave it for now and discuss it with @JenniferGold tomorrow to see what she thinks. I'll add this to our agenda.

**Comment by JenniferGold** [comment]
Yes, let’s brainstorm this tomorrow.

**Comment by alexgleason** [comment]
We're sticking with Order.

**Comment by marykatefain** [comment]
Order is fine, may be different types of orders in the future

**Comment by marykatefain** [comment]
Order for pickup, services, deliveries
