### ISSUE TITLE
Rethink "Active" vs "Upcoming" order UI?

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#70]
This differentiation seems a bit confusing. I can foresee a user seeing this screen and the message below the "active orders" section saying "you have no active orders, would you like to submit one?" and thinking "What the heck? I just submitted an order for tomorrow!"

I think we can probably just lump these two together and put the status bar to work. For example a order that is open but not active yet could have a grayed-out status bar. (The current way the bar updates is actually super weird and confusing anyways and fixing this may help.)

**Comment by alexgleason** [comment]
Good call, I created a new filter called "open" for Orders which means that the order is not completed but may not yet have started either. The OrderList view now displays open orders at the top followed by the order history in bd3d796470c16d0527c89860ea4d93672f066d48

**Comment by alexgleason** [comment]
Reopened because all open orders look visually the same, but upcoming orders should appear differently than active orders.

**Comment by alexgleason** [comment]
![screenshot-2018-1-11 gardenhub 2](https://user-images.githubusercontent.com/3639540/34847324-f156072e-f6e8-11e7-927c-064ddc90b4cf.png)

New UI in 1e8d485ec96e8bd79d8146ba298f6e32498233a4

**Comment by marykatefain** [comment]
This looks good to me! Thanks!
