### ISSUE TITLE
Replace "you donated X lbs of food" with Activity notification

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#72]
Just an idea, but I think it would be cool if on the home screen instead of this "You donated x lbs of food" (which was really just a placeholder until we found a good thing to show there, we showed the latest relevant activity notification.

So for example if they have an active order where John picked tomatoes today, they may see a status notification "John picked your tomatoes today! Click here to see all activity"

**Comment by alexgleason** [comment]
I ended up just removing it entirely.
