### ISSUE TITLE
Allow user to add new crop in "New Order" screen

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#74]
I think we will want to allow users to be able to add a crop to their plot directly in the "New Order" form "select crops" section.  This could look like a popup over the New Order screen where they edit the crops in their plot and then save and close the screen. Hoping that since the API is included there that it will be possible to then live-update the crops list in the order form?

**Comment by alexgleason** [comment]
I added a button to the order form, but all it does is takes the user to the edit plot screen for the selected plot. I'm concerned about getting any fancier than that for the first release. There are so many tests that still need to be written and if I can finish this first sprint today I'd rather use the remaining time writing those tests so I know the existing functionality won't break, opposed to writing a bunch of complex code to make this work and not having tests for it.

Anyway, it's in commit 35408db5ae8e4b51d31c0544b341b24d97bb41cc and there's a screenshot.

![screenshot from 2018-01-20 20 29 40](https://user-images.githubusercontent.com/3639540/35189829-370f9c64-fe21-11e7-886c-79599c20c4be.png)

**Comment by marykatefain** [comment]
Good call, I agree this is fine for now.
