### ISSUE TITLE
Consider who has permission to do what

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#79]
- Who can add a user to a plot? Who can remove them?
- Can there be more than one user on a plot? Does one have ability to remove the other?
- Who can add a plot to a garden? Who can remove it?
- Who can add a GM to a garden? Who can remove them?
- Can there be more than one GM on a garden? Does one have ability to remove the other?
- Who can add a garden to an affiliation? Who can remove it?
- Who can add a new affiliation? Who can remove it?
- Who manages affiliations, and what special permissions does this grant them?

**Comment by alexgleason** [comment]
Below are my interpretations. I've been developing the site so far based on these assumptions:

> - Who can add a user to a plot? Who can remove them?

A manager of that plot's garden can add or remove any user from a plot, including themself. A gardener of the plot can add or remove any user from the plot, excluding themself.

> - Can there be more than one user on a plot? Does one have ability to remove the other?

Yes and yes.

> - Who can add a plot to a garden? Who can remove it?

A manager of a garden can add or remove any plot in that garden.

> - Who can add a GM to a garden? Who can remove them?

A GardenHub admin can add or remove a GM from a garden. A GM can add or remove any other GM from a garden.

> - Can there be more than one GM on a garden? Does one have ability to remove the other?

Yes and yes.

> - Who can add a garden to an affiliation? Who can remove it?

A garden manager can add gardens they manage to an affiliation.

> - Who can add a new affiliation? Who can remove it?

GardenHub admins can add and remove affiliations.

> - Who manages affiliations, and what special permissions does this grant them?

GardenHub admins manage affiliations. Though I am unclear how affiliations affect the permissions of its members.

If we anticipate there being issues where certain gardeners or garden managers will be fighting each other to claim stake over a certain resource in the app, maybe we could have a concept of an "initial owner" of the resource who cannot be removed. This would be more work though and seems unlikely.

My personal biggest question is, how do affiliations affect permissions? eg: Garden A and Garden B are affiliated by Affiliation X. James is a manager of Garden A, so can he manage Garden B by virtue of the affiliation? etc.

**Comment by JenniferGold** [comment]
Not sure regular gardeners should be able to add or delete any other
gardeners.  Let’s discuss this tomorrow.  It gets complicated when people
share plots.  And sharing plots aside, you’d be surprised the arguments
people get into about every little thing.

At this stage in GardenHub’s evolution, affiliations do not affect
permissions.  Only a garden manager of a particular garden can manage that
garden.  The major next step for affiliations (and not on this year’s
GardenHub roadmap) would be to create an affiliation entity, managers, and
a communication function for affiliations to interact with their member
gardens, mostly about news and events.

**Comment by marykatefain** [comment]
I believe this is under control now.
