### ISSUE TITLE
Edit homepage button language for GMs

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#82]
**Instead of:** New Order, View my Orders, and View my Plots

**I propose:** New Order, Upcoming Orders, and Manage Plots

Although the buttons will do the same thing, I think this language is more indicative of what a GM would be looking to do. I recognize that this makes the home page a little more complicated and it's not as simple as just changing the text because we would have to render different text depending on if they manage a garden or not. I'm labeling this for 0.5.0 but I will try to work on it myself tonight as I know your plate is full (@alexgleason).

![screenshot from 2018-01-11 18 18 55](https://user-images.githubusercontent.com/17955536/34852294-e8c1feac-f6fb-11e7-9627-50e30e804ac2.png)

**Comment by alexgleason** [comment]
Changed via b14e11bc8e4f4d979e6ff1380c01c86feccc7c63

Not sure I totally agree with this change, or even the current homepage design as it stands, but for now I'll take it.
