### ISSUE TITLE
Update UI to reflect "Select All" IRL meaning, for gardener and picker

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#90]
1) Gardeners should have some sort of visual indication that "select all" means ALL crops on the plot IRL, not necessarily just the crops they put into the app. 

2) Pickers should have a way to know when "select all" has been chosen - this will likely need to become a form field, now.

**Comment by alexgleason** [comment]
Added via 4afdfb068a780aaf0ec40c4c041b3f8d38f71946

It looks like this:

![screenshot from 2018-01-20 19 33 15](https://user-images.githubusercontent.com/3639540/35189678-6d56b27e-fe1e-11e7-87f7-e94906a96010.png)

If you enable the switch, the crop selection gets hidden:

![screenshot from 2018-01-20 19 33 26](https://user-images.githubusercontent.com/3639540/35189681-7fab9cdc-fe1e-11e7-9812-e9e8af49c595.png)

Finally, the order cards (and the detail pages) convey that all crops should be picked:

![screenshot from 2018-01-20 20 12 56](https://user-images.githubusercontent.com/3639540/35189687-9300788e-fe1e-11e7-9ee2-d1b786e6a787.png)

**Comment by marykatefain** [comment]
Wow this is great. Good thinking on how to handle this!
