### ISSUE TITLE
Allow garden managers to create plots

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#94]
At the moment only admins can create plots. Obviously, the manager of a garden should have the ability to add a new plot to their garden.

**Comment by marykatefain** [comment]
True ^

**Comment by JenniferGold** [comment]
True.

**Comment by alexgleason** [comment]
d58c0a67e902bb1536aca91be7203d6b3a1f6faa adds basic functionality for this. I'll refine it along with #62.
