### ISSUE TITLE
Hide the create order screen from users that can't place an order on any plots

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#96]
In the case a user can't place an order on any plots and also isn't a picker, the "create order" view should reject them and the buttons to "create a new order" shouldn't be visible to them.

It's sort of an edge case since in reality this should never happen, but if it ever did it would be confusing to users. Related to #54.

**Comment by JenniferGold** [comment]
the edges are everything.

thank you.

**Comment by marykatefain** [comment]
So got I so a user who shouldn't can't see the New Order page, but Django now boots the user to a login screen and tries to have them login and redirect back to the same page, which they still can't do. It creates an endless loop. 

I recommend creating a "Permission Denied" page that the user gets redirected to anytime the test_func() fails. This could be a simple page like "Sorry, you do not have permission to access this page. Please contact your Garden Manager or a Garden Hub Admin if you feel this a mistake."  Will make a new issue for this.

Back to the topic of this issue specifically, it's awkward that they see the button to submit a new order still. I'm going to filter that out in the template in place of some backup text like "You aren't assigned to any plots! Please contact your GM".

**Comment by alexgleason** [comment]
I made a fallback screen to handle this in 1247dda327ce9fac31b87dd9bb793b383edaa9b3

![screen shot 2018-01-27 at 21 35 00](https://user-images.githubusercontent.com/3639540/35478377-06cee684-03aa-11e8-9ae6-3fd87291550a.png)

**Comment by marykatefain** [comment]
Awesome
