### ISSUE TITLE
Add phone number field to user profile

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#98]
1. Should this be required?
2. Do we have the user enter it when they create their account?

**Comment by alexgleason** [comment]
I think we should use this library https://github.com/stefanfoulis/django-phonenumber-field

I think it's important that we *do* store phone numbers in the database the right way from the start; no cutting corners and using normal text fields. If we want to programatically text people ever in the future we'll need the phone numbers to be formatted properly.

**Comment by JenniferGold** [comment]
I think phone number is a required field.

Thank you very much for dealing with this now.  Communication is absoltely
critical to the long term success of GardenHub, and a phone number is the
one thing everyone has.

And good point about the text messages.

**Comment by alexgleason** [comment]
I thought about it, and I'm not sure phone number should be a required field. Here is my reasoning:

1. Not everyone does actually have a phone number. Case in point, my roommate who didn't have a working phone for 2 months and was writing down our phone numbers at job interviews. Phone plans are expensive. Also, making this field required would affect every user, including pickers, who I think would be more likely to not have a phone number.

2. Email address already is required. Users confirm their email address when they register. If you don't have an email address, you can sign up for one for free. This is unlike a phone number, where you have to pay money to get one if you don't have one.

3. Email notifications may be slower than texts, but GardenHub really isn't an emergency response type situation anyway. I think it's perfectly reasonable to place an order for something and then except to receive an email confirmation when it's ready or if there's anything wrong.

4. Many people wouldn't want to give out their phone number for privacy reasons, or would prefer to opt out of calls and texts.

I'm guessing the main reason to want user's phone numbers is so we can call people if something goes wrong. Personally I think even in that case sending an email is fine. Some people have phone anxiety and won't answer, and many people refuse to answer calls from numbers they don't know. I'm not sure calling people is really the best way to deal with this.

The main benefit of storing users' phone numbers is to *give them the option* to receive alerts via SMS if they're a user who is really eager to receive status updates. An email is like a whisper and a text is like a scream. Casual users will probably prefer email only, and really invested users may prefer SMS.

**Comment by alexgleason** [comment]
Shit, also, there's no way of knowing whether the phone number a user enters is real or not without having some sort of SMS confirmation... so for all we know they give us a random phone number and we really annoy that person by mistake.

**Comment by marykatefain** [comment]
For now please just allow people to enter phone number without worrying about validation.
